### ISSUE TITLE
Link to github are not working

### ISSUE THREAD

**Issue by Wesseldr** [airbnb/backpack#7]
On the webpage: http://airbnb.github.io/backpack/
Every link to the git repository has the wrong link.
Current link: http://github.com/airbnb/backpack.js

Should become: https://github.com/airbnb/backpack

Probably best to run a grep -r over the source folder as it is in several places :)
Going to give the lib a spin. Looks good! Thanks for sharing on github.

Wessel

**Comment by ljharb** [comment]
These should be fixed with #8 and #9.
